export { DashboardPage } from './DashboardPage'
export { AlertsPage } from './AlertsPage'
export { InvestigationPage } from './InvestigationPage'
export { AnalyticsPage } from './AnalyticsPage'
export { SettingsPage } from './SettingsPage'
